# Generated by Django 3.2.15 on 2023-03-07 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='제목')),
                ('category', models.CharField(blank=True, choices=[('MIRACLE', '기상'), ('HOMEWORK', '숙제')], max_length=100, null=True, verbose_name='카테고리')),
                ('goal', models.CharField(blank=True, max_length=255, null=True, verbose_name='목표')),
                ('is_alarm', models.BooleanField(default=False, verbose_name='알림 여부')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저 ID')),
            ],
            options={
                'verbose_name': '할 일',
                'db_table': 'routine',
            },
        ),
        migrations.CreateModel(
            name='RoutineResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('result', models.CharField(blank=True, choices=[('NOT', '안함'), ('TRY', '시도'), ('DONE', '완료')], max_length=100, null=True, verbose_name='결과')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.routine', verbose_name='할 일 ID')),
            ],
            options={
                'verbose_name': '할 일 수행 결과',
                'db_table': 'routine_result',
            },
        ),
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('day', models.CharField(blank=True, choices=[('MON', '월요일'), ('TUE', '화요일'), ('WEB', '수요일'), ('THU', '목요일'), ('FRI', '금요일'), ('SAT', '토요일'), ('SUN', '일요일')], max_length=100, null=True, verbose_name='요일')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.routine', verbose_name='할 일 ID')),
            ],
            options={
                'verbose_name': '할 일 ',
                'db_table': 'routine_day',
            },
        ),
    ]
