# REGEX
PASSWORD_REGEX = r'^(?=.*[\d])(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*()])[\w\d!@#$%^&*()]{8,}$'

# STATUS MESSAGE
STATUS_MESSAGE_ROUTINE_CREATE_OK = 'ROUTINE_CREATE_OK'
STATUS_MESSAGE_ROUTINE_LIST_OK = 'ROUTINE_LIST_OK'
STATUS_MESSAGE_ROUTINE_DETAIL_OK = 'ROUTINE_DETAIL_OK'

# RESPONSE MESSAGE
RESPONSE_MESSAGE_REGISTER_SUCCESS = 'register success'
RESPONSE_MESSAGE_LOGIN_SUCCESS = 'login success'
RESPONSE_MESSAGE_LOGOUT_SUCCESS = 'logout success'

RESPONSE_MESSAGE_ROUTINE_CREATE_SUCCESS = 'You have successfully created the routine.'
RESPONSE_MESSAGE_ROUTINE_LOOKUP_SUCCESS = 'Routine lookup was successful.'


